apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux
spec:
  interval: 5m
  chart:
    spec:
      chart: https://prometheus-community.github.io/helm-charts
      version: '25.14.x'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 1m