apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: velero
      version: '5.4.x'
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
      interval: 1m
  releaseName: velero
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment