apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: prometheus
      version: '25.14.x'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  releaseName: prometheus
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment