apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: "7.3.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1m
  releaseName: grafana
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    rbac:
      namespaced: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        #- mikael.cloud
        - dev.mikael.cloud
      tls:
        - secretName: mikael.cloud
          hosts:
            #- mikael.cloud
            - dev.mikael.cloud
