name: Lint & Deploy Policy

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    paths:
      - policy/**

jobs:
  Lint-Policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Lint policies
        run: |
          curl -L -o regal "https://github.com/StyraInc/regal/releases/latest/download/regal_Linux_x86_64"
          chmod +x regal
          regal lint policy/

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: opa build -b .
